name: Build web-core Image

on:
  push:
    branches:
      - main
      - dev
      - fuse-dev
  release:
    types: [released]

env:
  PROJECT_ID: safe-402107
  SERVICE_NAME: safe-wallet-web

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add secrets to .env
        run: |-
          echo "NEXT_PUBLIC_WC_PROJECT_ID=${{ secrets.WC_PROJECT_ID }}" > .env &&
          echo "NEXT_PUBLIC_SOCIAL_WALLET_OPTIONS_STAGING=${{ secrets.SOCIAL_WALLET_OPTIONS }}" >> .env &&
          echo "NEXT_PUBLIC_SOCIAL_WALLET_OPTIONS_PRODUCTION=${{ secrets.SOCIAL_WALLET_OPTIONS }}" >> .env

      # Configure Workload Identity Federation and generate an access token.
      # - id: 'auth'
      #   name: 'Authenticate to Google Cloud'
      #   uses: 'google-github-actions/auth@v1'
      #   with:
      #     workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
      #     service_account: '${{ secrets.RUN_SA_EMAIL }}'

      # Alternative option - authentication via credentials json
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Build and push image to Google Container Registry
      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: |-
          gcloud builds submit \
            --quiet --async \
            --config=scripts/github/cloudbuild.yml \
            --substitutions=TAG_NAME="${GITHUB_REF##*/}"

      - name: Build
        if: github.ref == 'refs/heads/fuse-dev'
        run: |-
          gcloud builds submit \
            --quiet --async \
            --config=scripts/github/cloudbuild.yml \
            --substitutions=TAG_NAME="fuse-dev"

      - name: Build
        if: github.ref == 'refs/heads/dev'
        run: |-
          gcloud builds submit \
            --quiet --async \
            --config=scripts/github/cloudbuild.yml \
            --substitutions=TAG_NAME="dev"

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: |-
          gcloud builds submit \
            --quiet --async \
            --config=scripts/github/cloudbuild.yml \
            --substitutions=TAG_NAME="main"
